spring:
  application:
    name: accountHistory
  datasource:
    url: jdbc:mysql://localhost:3306/account_history?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
#      uri: mongodb://localhost:27017/account_history
#      username: root
#      password: 1234
      uri: ${SPRING_DATA_MONGODB_URI}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
server:
  port: 8080