spring:
  application:
    name: accountHistory
  datasource:
    url: jdbc:mysql://localhost:3306/account_history?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/account_history

server:
  port: 8080